# Generated by Django 5.2.6 on 2025-10-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preferences", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="preference",
            index=models.Index(fields=["user"], name="preferences_user_id_3d1fec_idx"),
        ),
        migrations.AddIndex(
            model_name="preference",
            index=models.Index(
                fields=["updated_at"], name="preferences_updated_09ff4f_idx"
            ),
        ),
    ]
