version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENVIRONMENT=prod
      - DB_NAME=db_production.sqlite3
    volumes:
      - ./data:/data
      - ./db:/app/db  # SQLite database persistence
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - uniquest-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - uniquest-network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  uniquest-network:
    driver: bridge