# Generated by Django 5.2.6 on 2025-10-10 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university_ref",
                    models.CharField(
                        help_text="OpenAlex ID or canonical identifier for the university",
                        max_length=255,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True,
                        help_text="Specific program or degree recommended",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Recommendation score from 0.0 to 1.0",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        help_text="Explanation for why this university was recommended"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Filters used when generating this recommendation",
                    ),
                ),
                (
                    "weights",
                    models.JSONField(
                        default=dict,
                        help_text="Weights used when generating this recommendation",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendations",
                "ordering": ["-generated_at", "-score"],
            },
        ),
    ]
