# Generated by Django 5.2.6 on 2025-10-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "-generated_at"], name="recommendat_user_id_e74f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["university_ref"], name="recommendat_univers_d0d7e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["-score"], name="recommendat_score_b06080_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["-generated_at"], name="recommendat_generat_387346_idx"
            ),
        ),
    ]
