# Generated by Django 5.2.6 on 2025-10-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "-created_at"], name="feedback_user_id_88c7db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["recommendation"], name="feedback_recomme_08c2c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["rating"], name="feedback_rating_ed839f_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="feedback_created_d6e06a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("user", "recommendation")},
        ),
    ]
