# Generated by Django 5.2.6 on 2025-11-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_rank', models.IntegerField()),
                ('institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('quality_of_education', models.FloatField(blank=True, null=True)),
                ('alumni_employment', models.FloatField(blank=True, null=True)),
                ('quality_of_faculty', models.FloatField(blank=True, null=True)),
                ('publications', models.FloatField(blank=True, null=True)),
                ('influence', models.FloatField(blank=True, null=True)),
                ('citations', models.FloatField(blank=True, null=True)),
                ('broad_impact', models.FloatField(blank=True, null=True)),
                ('patents', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
