# Generated by Django 5.2.6 on 2025-10-10 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPA on 4.0 scale",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(4.0),
                        ],
                    ),
                ),
                (
                    "test_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Test scores like SAT, ACT, GRE, TOEFL, etc.",
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True, help_text="Academic and career interests"
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True, help_text="Educational and career goals"
                    ),
                ),
                (
                    "preferred_regions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred regions/countries",
                    ),
                ),
                (
                    "country_preference",
                    models.CharField(
                        blank=True,
                        help_text="ISO 2-letter country code for primary preference",
                        max_length=2,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum budget in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum budget in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "student_profiles",
            },
        ),
    ]
