# Generated by Django 5.2.6 on 2025-10-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["user"], name="student_pro_user_id_f42457_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["country_preference"], name="student_pro_country_914917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["created_at"], name="student_pro_created_cc0720_idx"
            ),
        ),
    ]
